### ISSUE TITLE
Option to disable update checker

### ISSUE THREAD

**Issue by FireController1847** [tom2208/ChestCleaner#15]
I would like the ability to disable update checking, as the message being sent to me every time I log in is quite annoying, thanks! :)

**Comment by tom2208** [comment]
Done: https://github.com/tom2208/ChestCleaner/commit/d1f94e1109d61dc37c9ed0d345e5b70bf2d22739
You wille be able to en-/disable the UpdateChecker in the config.yml with the next released version.

At the moment you can try it solve the problem with the permission "chestcleaner.update": https://github.com/tom2208/ChestCleaner/wiki#other-features

**Comment by FireController1847** [comment]
Thanks :)
