### ISSUE TITLE
Maven build encoding issue

### ISSUE THREAD

**Issue by tom2208** [tom2208/ChestCleaner#20]
It seems like there is an issue with the maven build of chestcleaner.
The color code for instance §6 is displayed in a worng way, the color works but it brings a 'T' or 'Â' like sybole with it (in console or ingame chat). This happens in the console and in the ingame chat.

Further the wrong plugin version gets displayed in the console (1.6.2 instead of 1.8).
Some example images: 
https://imgur.com/meg39v7
https://imgur.com/gvUJtKQ

**Comment by brettp** [comment]
The colors should have been resolved in #17 by using color constants and switching to the hex string (`\u00A7`) for the `$` to `§` conversation. Are you seeing it somewhere else?

> Further the wrong plugin version gets displayed in the console (1.6.2 instead of 1.8).

I don't think this is related.

**Comment by tom2208** [comment]
The Strings are getting loaded from the ResourceBundle object out of a .properties file. In there you have § characters. That should cause the issue. I will try to replace the symboles there, but it should be a user friendly solution, because they want to edit these .properties files for custom strings or a custom language file.

To the version tag: I don't think its an encoding issue, but its an issue with the maven build, because the eclipse builded verion is showing the correct version. Tbh. i don't realy understand where this verison number '1.6.2' comes from.

**Comment by brettp** [comment]
For the prop strings, can you replace the `§` with a `&` and do a string replacement in code? Similar to the /commands.

**Comment by tom2208** [comment]
I give it a try.

**Comment by tom2208** [comment]
Didnt solved the problem. But i found it though. Its not an issue of the code it was an issue of my project folder. I dont know why but as i cloned a new repository on my desktop, created a new build and ran it everything worked fine.
