### ISSUE TITLE
Adding Filters to the sorting system.

### ISSUE THREAD

**Issue by tom2208** [tom2208/ChestCleaner#26]
I would prefer a clearer, reusable and more adjustable sorting system. For this we should rework the whole sorting system a bit.
Creating filter objects you can combine for a sorting configuration. For instance CreariveTabFilter, ShapeFilter, etc.
The the server operators can set a combination of filters as the default state and the normal players can create their own individual filter combination. 

The rules of the combination should be:
- a filter should categorize all given materials
- a filter should include more than one potential item for the most categories

filters are creating categories the next splits each category into other sub categories (may include a not effected category, but should categorize all materials) etc.
The order of categories is the sorting. After all other filters are applited the items in the first category will come first in the order they are saved in the category.
But we have to differ between filters and evaluators. Filters are creating categories, that would make no sense for evaluators. For instance the alphabetical evaluator, each item would have its own category. Filters are splitting materials into categories and are sorting the order of the categories then. Evaluators are compairing items.

Example:
{CreativeTabFliter, ShapeFilter, AlphabeticleEvaluator}
CreativeTabFilter => 10 CreativeTab categories
=> each of this categories would call the next filter ShapeFilter => creating new categories of the new filter => sorting the sub categories of ShapeFilter with the  AlphabeticleEvaluator.

A visualition would look a bit like the visualition of merge sort (but with bigger groups of elements before starting to merge) (https://en.wikipedia.org/wiki/File:Merge_sort_algorithm_diagram.svg).

Pros:

easy to adjust, reuse
easy to create new filters
easy to safe the configuration of the players
easy to save player configurations
players can customize their own sortering
Cons:

you have to find abstraction levels to get the sorting you want, you can't just save a list of 900 Elements. You have to find the right combination of filters.
By the way: the playerconfig.yml is for the individual playerdata, generell configurations are saved in the config.yml

**Comment by leanNiki** [comment]
Implemented as Categories, see https://github.com/tom2208/ChestCleaner/wiki/Categories-2.0
