### ISSUE TITLE
Provide sample config.yml instead of writing defaults from Java Code

### ISSUE THREAD

**Issue by leanNiki** [tom2208/ChestCleaner#28]
Instead of initializing the config.yml from Java and having all the default values inside the code, we should create a sample config.yml Resource (like the *.properties files) which contains all default values.

**Comment by tom2208** [comment]
https://github.com/tom2208/ChestCleaner/commit/8afc50c3162c15b17b6c4756bd61d24bd3fb9ce2
config.yml is added, further it gets loaded form the jar into the resouce folder of the plugin.
