### ISSUE TITLE
Toggle chat notification upon cleaning/sorting

### ISSUE THREAD

**Issue by emilianocaro** [tom2208/ChestCleaner#37]

**Comment by tom2208** [comment]
Chat notifications and sounds are now toggleable (only in general, individual configuration will follow) https://github.com/tom2208/ChestCleaner/commit/1297f99b68c19b9e89eb6ee99b23c799f887e3ae

**Comment by tom2208** [comment]
The feature is implemented with https://github.com/tom2208/ChestCleaner/commit/f51ecd276a07e28a0e405d5526add05bd16a9f6f.
