### ISSUE TITLE
Is autorefilling consumables working properly?

### ISSUE THREAD

**Issue by 0xBADDCAFE** [tom2208/ChestCleaner#38]
I read the document for autorefill (https://github.com/tom2208/ChestCleaner/wiki/Autorefill-2.0) and try below setting in config.yml

```
refill:
  blocks: true
  consumables: true
```

It seems work for block, but seems not work for consumables. Below gif reproduce steps:

- Put oak planks in toolbar and inventory, wooden shovels in toolbar and inventory.
- Put all oak planks to field. It refilled automatically when put last one.
- Consume shovel to make grass paths. When broken the shovel, hand is empty and shovel still exists in inventory.

![ezgif-1-7d37ff6a97af](https://user-images.githubusercontent.com/599164/83175180-7a56f500-a156-11ea-89b8-1996e19b3bc1.gif)

Is this behavior expected?

```
CraftBukkit version git-Spigot-e7dc2f5-a8ec1d6 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Paper version git-Paper-318 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

**Comment by tom2208** [comment]
Consumables are stuff like food (a shovel is not a consumable). But to add a refill option for tools is a great idea! We will implement that.

**Comment by 0xBADDCAFE** [comment]
Oh sorry, I've misunderstood about "consumable" in Minecraft. Thanks to consider about tool refilling. I hope to implement it.

**Comment by tom2208** [comment]
Autorefill is now supported for breakables like tools. Admin configuration is supported too. Individual configuration will follow. https://github.com/tom2208/ChestCleaner/commit/a867a45a6706acde3fcc70e0be14af482695886b

**Comment by tom2208** [comment]
Individual configuration was added.
https://github.com/tom2208/ChestCleaner/commit/6dfe8ea70e515f7dbb854f45fcf4dda40163e29b

Very nice Bug-review btw. thank you!
