### ISSUE TITLE
UTF-8 encoding?

### ISSUE THREAD

**Issue by tom2208** [tom2208/ChestCleaner#39]
A user reported an issue: he can't use his own language because of "ANSI" encoding.

**Comment by tom2208** [comment]
The Java lib uses "ISO-8859-1" encoding. Will be a bit tricky to work around.

**Comment by ahdg6** [comment]
It's strange,In my tests, I can use the simplified Chinese translation(UTF-8) normally.

**Comment by tom2208** [comment]
I think the guy who reported the issue used arabic characters.
