### ISSUE TITLE
TPS sudden lag spike 

### ISSUE THREAD

**Issue by blek-id** [tom2208/ChestCleaner#40]
When player is placing skull, it drops the server's TPS, and there's an event that is called. I've been able to capture it in spark, you can see it below. 

Here's my server version:
Paper 1.15.2 build 378
chestcleaner 2.0.2

https://spark.lucko.me/#bHAJok8mXa

**Comment by tom2208** [comment]
Why do you think it's an ChestCleaner issue?

**Comment by blek-id** [comment]
Sorry about this, apparently it's paper's issue. It changed how they load player skull for GUI hence the lag. Will close this now
