### ISSUE TITLE
Autorefill deleting items in certain situations

### ISSUE THREAD

**Issue by sh1mrr4** [tom2208/ChestCleaner#41]
Hey,

I am encountering an issue with the autorefill feature in certain situations. If the last block of something in the hotbar is placed, but placing the block is prevented by another plugin (for example if somebody places a block in a region proteced by WorldGuard), the item moved to the hotbar by autorefill overwrites the item that wasn't actually placed.

This seems to be a general issue involving all kinds of plugins, that prevent block-placement in certain situations, so a fix for this handy feature would be greatly appreciated.

Version ChestCleaner: 2.0.2
Server: Paper 1.15.2-378

Best regards,
sh1mrr4

**Comment by tom2208** [comment]
Thank you for this report, we will fix this in the next version.

**Comment by tom2208** [comment]
Fixxed: https://github.com/tom2208/ChestCleaner/commit/ac3d710d2abac3c2208d469c959953b702e33c9d
