### ISSUE TITLE
A blacklist for autorefill

### ISSUE THREAD

**Issue by sh1mrr4** [tom2208/ChestCleaner#43]
Hey, thanks a lot for the recent update!

We are currently still experiencing an issue with the autorefill feature. We use a plugin called Wildstacker to limit the number of spawners players can place in a chunk, however, when that plugin denies a spawner placement, the previously reported [issue](https://github.com/tom2208/ChestCleaner/issues/41) still occurs, even though it is fixed for WorldGuard regions.

Now, I think it would be futile trying to add support for all plugins out there, so a simple blacklist for autorefill, where you could just add the problematic items in cases like this would do the trick. Since there are already blacklists for sorting and stacking it would make sense to have one for this feature as well I guess.

Thanks a lot again for your effort!

sh1mrr4

**Comment by tom2208** [comment]
Good idea! I will implement that!

**Comment by tom2208** [comment]
Done! https://github.com/tom2208/ChestCleaner/commit/3c8822729f8286cc167e83a9d9cde44db60b0a4e
