### ISSUE TITLE
Hoe is removed/replaced by dirt when using it on Coarse dirt

### ISSUE THREAD

**Issue by thyraxx** [tom2208/ChestCleaner#51]
This only works when you have dirt in your inventory.
When you use a hoe on Coarse dirt, the hoe will be replaced by dirt from your inventory ending up without a hoe after using once.

**Comment by tom2208** [comment]
Thank you for the report i will fix this soon!

**Comment by tom2208** [comment]
Fixed with: https://github.com/tom2208/ChestCleaner/commit/f71c4c2109cdf2164973c2ae51118d37a8afefd9
