### ISSUE TITLE
Autorefill armor replaces item in off-hand

### ISSUE THREAD

**Issue by VishBK** [tom2208/ChestCleaner#52]
When armor breaks, autorefill puts the new armor in the off-hand, but replaces whatever's there, such as a shield.

**Comment by tom2208** [comment]
Thank you for the report i will check this out.

**Comment by tom2208** [comment]
Fixed with: https://github.com/tom2208/ChestCleaner/commit/f71c4c2109cdf2164973c2ae51118d37a8afefd9
