### ISSUE TITLE
Error preventing plugin from loading in paper 1.15.2

### ISSUE THREAD

**Issue by sh1mrr4** [tom2208/ChestCleaner#56]
Hey, 

I get the following error on start-up when trying to use the most recent version of ChestCleaner:

[https://pastebin.com/1VmJDmsp](https://pastebin.com/1VmJDmsp)

Server version: Paper 1.15.2 - 389
ChestCleaner: 2.3.2

Let me know if you need to know anything else :)

**Comment by tom2208** [comment]
Yea I know what wents wrong. Thank you for the report! I will fix this!

**Comment by tom2208** [comment]
Got fixed with: https://github.com/tom2208/ChestCleaner/commit/1ba47c6c66ed3ea1dd4baa732a594a58cec237d5
