### ISSUE TITLE
[BUG] Shields lost on break

### ISSUE THREAD

**Issue by SavePointSam** [tom2208/ChestCleaner#75]
**Describe the bug**

When a shield breaks while in the off-hand with a replacement in inventory. The replacement is lost rather than put on the off-hand. There is also no way to disable auto-refill for specific items that I can find through the in-game cli. For now, we have had to completely disable auto-refill.

**To Reproduce**
1. Create two shields, and keep in inventory
2. Hold 1 shield in off-hand and take damage until broken (Hoglins are good for this)
3. Observe that the second shield is lost

**Expected behavior**
The shield is either replaced automatically, or at least the second shield is not lost

**Screenshots**
I have a video recording I can provide upon request

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Spigot Version: For MC 1.19
 - Version: 2.4.1

**Additional context**
The server is mostly vanilla otherwise and the world was generated post-1.19 update.

**Comment by tom2208** [comment]
I was able to replicate the bug. Thanks for reporting.

**Comment by tom2208** [comment]
Fixed: [a49b23c3fe4ef72a3330f0e378033d0798a226d6](https://github.com/tom2208/ChestCleaner/releases/tag/v2.4.3), thank you for the report c:
