### ISSUE TITLE
Permission Chest Sorting

### ISSUE THREAD

**Issue by DokiDerg** [tom2208/ChestCleaner#84]
**Is your feature request related to a problem? Please describe.**
Kind of, I have a factions server, but the problem is you can sort chests that you usually could not open

**Describe the solution you'd like**
A way of typing, for example, `/sortchest` then waiting for you to open a chest, on the first **successful** chest it will sort, this can be used to make sure you are suppose to have access to this chest rather than messing with everybodys chest

**Describe alternatives you've considered**
Command then open, as said in solution
Another is to call the open chest event and see if it is canceled, if not then sort the chest

**Comment by tom2208** [comment]
You can already do a similar thing by using the cleaning item: https://github.com/tom2208/ChestCleaner/wiki/Cleaningitem#openevent

Then just disable the commands for your players.
Or use clicksort, that will just work in an opened inventory.
